// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BusinessCardComponent: typeof import('./src/components/BusinessCardComponent.vue')['default']
    BusinessFormComponent: typeof import('./src/components/BusinessFormComponent.vue')['default']
    IndustryOptionsComponent: typeof import('./src/components/IndustryOptionsComponent.vue')['default']
    LinkedinButtonComponent: typeof import('./src/components/LinkedinButtonComponent.vue')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
    ProfileCardComponent: typeof import('./src/components/ProfileCardComponent.vue')['default']
    ProfileFormComponent: typeof import('./src/components/ProfileFormComponent.vue')['default']
    SignInComponent: typeof import('./src/components/SignInComponent.vue')['default']
  }
}

export { }
