// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DemoComponent: typeof import('./src/components/DemoComponent.vue')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
  }
}

export { }
