// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChatComponent: typeof import('./src/components/ChatComponent.vue')['default']
    IdeaCardComponent: typeof import('./src/components/IdeaCardComponent.vue')['default']
    IndustryOptionsComponent: typeof import('./src/components/IndustryOptionsComponent.vue')['default']
    MessageComponent: typeof import('./src/components/MessageComponent.vue')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
    ProfileComponent: typeof import('./src/components/ProfileComponent.vue')['default']
    SignInComponent: typeof import('./src/components/SignInComponent.vue')['default']
    UserCardComponent: typeof import('./src/components/UserCardComponent.vue')['default']
  }
}

export { }
